export const coutries = [
  { name: "Afghanistan", flag: "🇦🇫", key: "AF", dial_code: "+93" },
  { name: "Åland Islands", flag: "🇦🇽", key: "AX", dial_code: "+358" },
  { name: "Albania", flag: "🇦🇱", key: "AL", dial_code: "+355" },
  { name: "Algeria", flag: "🇩🇿", key: "DZ", dial_code: "+213" },
  { name: "American Samoa", flag: "🇦🇸", key: "AS", dial_code: "+1684" },
  { name: "Andorra", flag: "🇦🇩", key: "AD", dial_code: "+376" },
  { name: "Angola", flag: "🇦🇴", key: "AO", dial_code: "+244" },
  { name: "Anguilla", flag: "🇦🇮", key: "AI", dial_code: "+1264" },
  { name: "Antarctica", flag: "🇦🇶", key: "AQ", dial_code: "+672" },
  { name: "Antigua and Barbuda", flag: "🇦🇬", key: "AG", dial_code: "+1268" },
  { name: "Argentina", flag: "🇦🇷", key: "AR", dial_code: "+54" },
  { name: "Armenia", flag: "🇦🇲", key: "AM", dial_code: "+374" },
  { name: "Aruba", flag: "🇦🇼", key: "AW", dial_code: "+297" },
  { name: "Australia", flag: "🇦🇺", key: "AU", dial_code: "+61" },
  { name: "Austria", flag: "🇦🇹", key: "AT", dial_code: "+43" },
  { name: "Azerbaijan", flag: "🇦🇿", key: "AZ", dial_code: "+994" },
  { name: "Bahamas", flag: "🇧🇸", key: "BS", dial_code: "+1242" },
  { name: "Bahrain", flag: "🇧🇭", key: "BH", dial_code: "+973" },
  { name: "Bangladesh", flag: "🇧🇩", key: "BD", dial_code: "+880" },
  { name: "Barbados", flag: "🇧🇧", key: "BB", dial_code: "+1246" },
  { name: "Belarus", flag: "🇧🇾", key: "BY", dial_code: "+375" },
  { name: "Belgium", flag: "🇧🇪", key: "BE", dial_code: "+32" },
  { name: "Belize", flag: "🇧🇿", key: "BZ", dial_code: "+501" },
  { name: "Benin", flag: "🇧🇯", key: "BJ", dial_code: "+229" },
  { name: "Bermuda", flag: "🇧🇲", key: "BM", dial_code: "+1441" },
  { name: "Bhutan", flag: "🇧🇹", key: "BT", dial_code: "+975" },
  {
    name: "Bolivia, Plurinational State of bolivia",
    flag: "🇧🇴",
    key: "BO",
    dial_code: "+591",
  },
  { name: "Bosnia and Herzegovina", flag: "🇧🇦", key: "BA", dial_code: "+387" },
  { name: "Botswana", flag: "🇧🇼", key: "BW", dial_code: "+267" },
  { name: "Bouvet Island", flag: "🇧🇻", key: "BV", dial_code: "+47" },
  { name: "Brazil", flag: "🇧🇷", key: "BR", dial_code: "+55" },
  {
    name: "British Indian Ocean Territory",
    flag: "🇮🇴",
    key: "IO",
    dial_code: "+246",
  },
  { name: "Brunei Darussalam", flag: "🇧🇳", key: "BN", dial_code: "+673" },
  { name: "Bulgaria", flag: "🇧🇬", key: "BG", dial_code: "+359" },
  { name: "Burkina Faso", flag: "🇧🇫", key: "BF", dial_code: "+226" },
  { name: "Burundi", flag: "🇧🇮", key: "BI", dial_code: "+257" },
  { name: "Cambodia", flag: "🇰🇭", key: "KH", dial_code: "+855" },
  { name: "Cameroon", flag: "🇨🇲", key: "CM", dial_code: "+237" },
  { name: "Canada", flag: "🇨🇦", key: "CA", dial_code: "+1" },
  { name: "Cape Verde", flag: "🇨🇻", key: "CV", dial_code: "+238" },
  { name: "Cayman Islands", flag: "🇰🇾", key: "KY", dial_code: "+345" },
  {
    name: "Central African Republic",
    flag: "🇨🇫",
    key: "CF",
    dial_code: "+236",
  },
  { name: "Chad", flag: "🇹🇩", key: "TD", dial_code: "+235" },
  { name: "Chile", flag: "🇨🇱", key: "CL", dial_code: "+56" },
  { name: "China", flag: "🇨🇳", key: "CN", dial_code: "+86" },
  { name: "Colombia", flag: "🇨🇴", key: "CO", dial_code: "+57" },
  { name: "Comoros", flag: "🇰🇲", key: "KM", dial_code: "+269" },
  { name: "Congo", flag: "🇨🇬", key: "CG", dial_code: "+242" },
  {
    name: "Congo, The Democratic Republic of the Congo",
    flag: "🇨🇩",
    key: "CD",
    dial_code: "+243",
  },
  { name: "Cook Islands", flag: "🇨🇰", key: "CK", dial_code: "+682" },
  { name: "Costa Rica", flag: "🇨🇷", key: "CR", dial_code: "+506" },
  { name: "Cote d'Ivoire", flag: "🇨🇮", key: "CI", dial_code: "+225" },
  { name: "Croatia", flag: "🇭🇷", key: "HR", dial_code: "+385" },
  { name: "Cuba", flag: "🇨🇺", key: "CU", dial_code: "+53" },
  { name: "Cyprus", flag: "🇨🇾", key: "CY", dial_code: "+357" },
  { name: "Czech Republic", flag: "🇨🇿", key: "CZ", dial_code: "+420" },
  { name: "Denmark", flag: "🇩🇰", key: "DK", dial_code: "+45" },
  { name: "Djibouti", flag: "🇩🇯", key: "DJ", dial_code: "+253" },
  { name: "Dominica", flag: "🇩🇲", key: "DM", dial_code: "+1767" },
  { name: "Dominican Republic", flag: "🇩🇴", key: "DO", dial_code: "+1849" },
  { name: "Ecuador", flag: "🇪🇨", key: "EC", dial_code: "+593" },
  { name: "Egypt", flag: "🇪🇬", key: "EG", dial_code: "+20" },
  { name: "El Salvador", flag: "🇸🇻", key: "SV", dial_code: "+503" },
  { name: "Equatorial Guinea", flag: "🇬🇶", key: "GQ", dial_code: "+240" },
  { name: "Eritrea", flag: "🇪🇷", key: "ER", dial_code: "+291" },
  { name: "Estonia", flag: "🇪🇪", key: "EE", dial_code: "+372" },
  { name: "Ethiopia", flag: "🇪🇹", key: "ET", dial_code: "+251" },
  {
    name: "Falkland Islands (Malvinas)",
    flag: "🇫🇰",
    key: "FK",
    dial_code: "+500",
  },
  { name: "Faroe Islands", flag: "🇫🇴", key: "FO", dial_code: "+298" },
  { name: "Fiji", flag: "🇫🇯", key: "FJ", dial_code: "+679" },
  { name: "Finland", flag: "🇫🇮", key: "FI", dial_code: "+358" },
  { name: "France", flag: "🇫🇷", key: "FR", dial_code: "+33" },
  { name: "French Guiana", flag: "🇬🇫", key: "GF", dial_code: "+594" },
  { name: "French Polynesia", flag: "🇵🇫", key: "PF", dial_code: "+689" },
  {
    name: "French Southern Territories",
    flag: "🇹🇫",
    key: "TF",
    dial_code: "+262",
  },
  { name: "Gabon", flag: "🇬🇦", key: "GA", dial_code: "+241" },
  { name: "Gambia", flag: "🇬🇲", key: "GM", dial_code: "+220" },
  { name: "Georgia", flag: "🇬🇪", key: "GE", dial_code: "+995" },
  { name: "Germany", flag: "🇩🇪", key: "DE", dial_code: "+49" },
  { name: "Ghana", flag: "🇬🇭", key: "GH", dial_code: "+233" },
  { name: "Gibraltar", flag: "🇬🇮", key: "GI", dial_code: "+350" },
  { name: "Greece", flag: "🇬🇷", key: "GR", dial_code: "+30" },
  { name: "Greenland", flag: "🇬🇱", key: "GL", dial_code: "+299" },
  { name: "Grenada", flag: "🇬🇩", key: "GD", dial_code: "+1473" },
  { name: "Guam", flag: "🇬🇺", key: "GU", dial_code: "+1671" },
  { name: "Guatemala", flag: "🇬🇹", key: "GT", dial_code: "+502" },
  { name: "Guinea", flag: "🇬🇳", key: "GN", dial_code: "+224" },
  { name: "Guinea-Bissau", flag: "🇬🇼", key: "GW", dial_code: "+245" },
  { name: "Guyana", flag: "🇬🇾", key: "GY", dial_code: "+592" },
  { name: "Haiti", flag: "🇭🇹", key: "HT", dial_code: "+509" },
  {
    name: "Heard Island and Mcdonald Islands",
    flag: "🇭🇲",
    key: "HM",
    dial_code: "+672",
  },
  {
    name: "Holy See (Vatican City State)",
    flag: "🇻🇦",
    key: "VA",
    dial_code: "+379",
  },
  { name: "Honduras", flag: "🇭🇳", key: "HN", dial_code: "+504" },
  { name: "Hong Kong", flag: "🇭🇰", key: "HK", dial_code: "+852" },
  { name: "Hungary", flag: "🇭🇺", key: "HU", dial_code: "+36" },
  { name: "Iceland", flag: "🇮🇸", key: "IS", dial_code: "+354" },
  { name: "India", flag: "🇮🇳", key: "IN", dial_code: "+91" },
  { name: "Indonesia", flag: "🇮🇩", key: "ID", dial_code: "+62" },
  {
    name: "Iran, Islamic Republic of Persian Gulf",
    flag: "🇮🇷",
    key: "IR",
    dial_code: "+98",
  },
  { name: "Iraq", flag: "🇮🇶", key: "IQ", dial_code: "+964" },
  { name: "Ireland", flag: "🇮🇪", key: "IE", dial_code: "+353" },
  { name: "Israel", flag: "🇮🇱", key: "IL", dial_code: "+972" },
  { name: "Italy", flag: "🇮🇹", key: "IT", dial_code: "+39" },
  { name: "Jamaica", flag: "🇯🇲", key: "JM", dial_code: "+1876" },
  { name: "Japan", flag: "🇯🇵", key: "JP", dial_code: "+81" },
  { name: "Jersey", flag: "🇯🇪", key: "JE", dial_code: "+44" },
  { name: "Jordan", flag: "🇯🇴", key: "JO", dial_code: "+962" },
  { name: "Kazakhstan", flag: "🇰🇿", key: "KZ", dial_code: "+7" },
  { name: "Kenya", flag: "🇰🇪", key: "KE", dial_code: "+254" },
  { name: "Kiribati", flag: "🇰🇮", key: "KI", dial_code: "+686" },
  {
    name: "Korea, Democratic People's Republic of Korea",
    flag: "🇰🇵",
    key: "KP",
    dial_code: "+850",
  },
  {
    name: "Korea, Republic of South Korea",
    flag: "🇰🇷",
    key: "KR",
    dial_code: "+82",
  },
  { name: "Kosovo", flag: "🇽🇰", key: "XK", dial_code: "+383" },
  { name: "Kuwait", flag: "🇰🇼", key: "KW", dial_code: "+965" },
  { name: "Kyrgyzstan", flag: "🇰🇬", key: "KG", dial_code: "+996" },
  { name: "Laos", flag: "🇱🇦", key: "LA", dial_code: "+856" },
  { name: "Latvia", flag: "🇱🇻", key: "LV", dial_code: "+371" },
  { name: "Lebanon", flag: "🇱🇧", key: "LB", dial_code: "+961" },
  { name: "Lesotho", flag: "🇱🇸", key: "LS", dial_code: "+266" },
  { name: "Liberia", flag: "🇱🇷", key: "LR", dial_code: "+231" },
  { name: "Libyan Arab Jamahiriya", flag: "🇱🇾", key: "LY", dial_code: "+218" },
  { name: "Liechtenstein", flag: "🇱🇮", key: "LI", dial_code: "+423" },
  { name: "Lithuania", flag: "🇱🇹", key: "LT", dial_code: "+370" },
  { name: "Luxembourg", flag: "🇱🇺", key: "LU", dial_code: "+352" },
  { name: "Macao", flag: "🇲🇴", key: "MO", dial_code: "+853" },
  { name: "Macedonia", flag: "🇲🇰", key: "MK", dial_code: "+389" },
  { name: "Madagascar", flag: "🇲🇬", key: "MG", dial_code: "+261" },
  { name: "Malawi", flag: "🇲🇼", key: "MW", dial_code: "+265" },
  { name: "Malaysia", flag: "🇲🇾", key: "MY", dial_code: "+60" },
  { name: "Maldives", flag: "🇲🇻", key: "MV", dial_code: "+960" },
  { name: "Mali", flag: "🇲🇱", key: "ML", dial_code: "+223" },
  { name: "Malta", flag: "🇲🇹", key: "MT", dial_code: "+356" },
  { name: "Marshall Islands", flag: "🇲🇭", key: "MH", dial_code: "+692" },
  { name: "Martinique", flag: "🇲🇶", key: "MQ", dial_code: "+596" },
  { name: "Mauritania", flag: "🇲🇷", key: "MR", dial_code: "+222" },
  { name: "Mauritius", flag: "🇲🇺", key: "MU", dial_code: "+230" },
  { name: "Mayotte", flag: "🇾🇹", key: "YT", dial_code: "+262" },
  { name: "Mexico", flag: "🇲🇽", key: "MX", dial_code: "+52" },
  {
    name: "Micronesia, Federated States of Micronesia",
    flag: "🇫🇲",
    key: "FM",
    dial_code: "+691",
  },
  { name: "Moldova", flag: "🇲🇩", key: "MD", dial_code: "+373" },
  { name: "Monaco", flag: "🇲🇨", key: "MC", dial_code: "+377" },
  { name: "Mongolia", flag: "🇲🇳", key: "MN", dial_code: "+976" },
  { name: "Montenegro", flag: "🇲🇪", key: "ME", dial_code: "+382" },
  { name: "Montserrat", flag: "🇲🇸", key: "MS", dial_code: "+1664" },
  { name: "Morocco", flag: "🇲🇦", key: "MA", dial_code: "+212" },
  { name: "Mozambique", flag: "🇲🇿", key: "MZ", dial_code: "+258" },
  { name: "Myanmar", flag: "🇲🇲", key: "MM", dial_code: "+95" },
  { name: "Namibia", flag: "🇳🇦", key: "NA", dial_code: "+264" },
  { name: "Nauru", flag: "🇳🇷", key: "NR", dial_code: "+674" },
  { name: "Nepal", flag: "🇳🇵", key: "NP", dial_code: "+977" },
  { name: "Netherlands", flag: "🇳🇱", key: "NL", dial_code: "+31" },
  { name: "Netherlands Antilles", flag: "", key: "AN", dial_code: "+599" },
  { name: "New Caledonia", flag: "🇳🇨", key: "NC", dial_code: "+687" },
  { name: "New Zealand", flag: "🇳🇿", key: "NZ", dial_code: "+64" },
  { name: "Nicaragua", flag: "🇳🇮", key: "NI", dial_code: "+505" },
  { name: "Niger", flag: "🇳🇪", key: "NE", dial_code: "+227" },
  { name: "Nigeria", flag: "🇳🇬", key: "NG", dial_code: "+234" },
  { name: "Niue", flag: "🇳🇺", key: "NU", dial_code: "+683" },
  { name: "Norfolk Island", flag: "🇳🇫", key: "NF", dial_code: "+672" },
  {
    name: "Northern Mariana Islands",
    flag: "🇲🇵",
    key: "MP",
    dial_code: "+1670",
  },
  { name: "Norway", flag: "🇳🇴", key: "NO", dial_code: "+47" },
  { name: "Oman", flag: "🇴🇲", key: "OM", dial_code: "+968" },
  { name: "Pakistan", flag: "🇵🇰", key: "PK", dial_code: "+92" },
  { name: "Palau", flag: "🇵🇼", key: "PW", dial_code: "+680" },
  {
    name: "Palestinian Territory, Occupied",
    flag: "🇵🇸",
    key: "PS",
    dial_code: "+970",
  },
  { name: "Panama", flag: "🇵🇦", key: "PA", dial_code: "+507" },
  { name: "Papua New Guinea", flag: "🇵🇬", key: "PG", dial_code: "+675" },
  { name: "Paraguay", flag: "🇵🇾", key: "PY", dial_code: "+595" },
  { name: "Peru", flag: "🇵🇪", key: "PE", dial_code: "+51" },
  { name: "Philippines", flag: "🇵🇭", key: "PH", dial_code: "+63" },
  { name: "Pitcairn", flag: "🇵🇳", key: "PN", dial_code: "+64" },
  { name: "Poland", flag: "🇵🇱", key: "PL", dial_code: "+48" },
  { name: "Portugal", flag: "🇵🇹", key: "PT", dial_code: "+351" },
  { name: "Puerto Rico", flag: "🇵🇷", key: "PR", dial_code: "+1939" },
  { name: "Qatar", flag: "🇶🇦", key: "QA", dial_code: "+974" },
  { name: "Romania", flag: "🇷🇴", key: "RO", dial_code: "+40" },
  { name: "Russia", flag: "🇷🇺", key: "RU", dial_code: "+7" },
  { name: "Rwanda", flag: "🇷🇼", key: "RW", dial_code: "+250" },
  { name: "Reunion", flag: "🇷🇪", key: "RE", dial_code: "+262" },
  { name: "Saint Barthelemy", flag: "🇧🇱", key: "BL", dial_code: "+590" },
  {
    name: "Saint Helena, Ascension and Tristan Da Cunha",
    flag: "🇸🇭",
    key: "SH",
    dial_code: "+290",
  },
  { name: "Saint Kitts and Nevis", flag: "🇰🇳", key: "KN", dial_code: "+1869" },
  { name: "Saint Lucia", flag: "🇱🇨", key: "LC", dial_code: "+1758" },
  {
    name: "Saint Pierre and Miquelon",
    flag: "🇵🇲",
    key: "PM",
    dial_code: "+508",
  },
  {
    name: "Saint Vincent and the Grenadines",
    flag: "🇻🇨",
    key: "VC",
    dial_code: "+1784",
  },
  { name: "Samoa", flag: "🇼🇸", key: "WS", dial_code: "+685" },
  { name: "San Marino", flag: "🇸🇲", key: "SM", dial_code: "+378" },
  { name: "Sao Tome and Principe", flag: "🇸🇹", key: "ST", dial_code: "+239" },
  { name: "Saudi Arabia", flag: "🇸🇦", key: "SA", dial_code: "+966" },
  { name: "Senegal", flag: "🇸🇳", key: "SN", dial_code: "+221" },
  { name: "Serbia", flag: "🇷🇸", key: "RS", dial_code: "+381" },
  { name: "Seychelles", flag: "🇸🇨", key: "SC", dial_code: "+248" },
  { name: "Sierra Leone", flag: "🇸🇱", key: "SL", dial_code: "+232" },
  { name: "Singapore", flag: "🇸🇬", key: "SG", dial_code: "+65" },
  { name: "Slovakia", flag: "🇸🇰", key: "SK", dial_code: "+421" },
  { name: "Slovenia", flag: "🇸🇮", key: "SI", dial_code: "+386" },
  { name: "Solomon Islands", flag: "🇸🇧", key: "SB", dial_code: "+677" },
  { name: "Somalia", flag: "🇸🇴", key: "SO", dial_code: "+252" },
  { name: "South Africa", flag: "🇿🇦", key: "ZA", dial_code: "+27" },
  { name: "South Sudan", flag: "🇸🇸", key: "SS", dial_code: "+211" },
  {
    name: "South Georgia and the South Sandwich Islands",
    flag: "🇬🇸",
    key: "GS",
    dial_code: "+500",
  },
  { name: "Spain", flag: "🇪🇸", key: "ES", dial_code: "+34" },
  { name: "Sri Lanka", flag: "🇱🇰", key: "LK", dial_code: "+94" },
  { name: "Sudan", flag: "🇸🇩", key: "SD", dial_code: "+249" },
  { name: "Suriname", flag: "🇸🇷", key: "SR", dial_code: "+597" },
  { name: "Svalbard and Jan Mayen", flag: "🇸🇯", key: "SJ", dial_code: "+47" },
  { name: "Eswatini", flag: "🇸🇿", key: "SZ", dial_code: "+268" },
  { name: "Sweden", flag: "🇸🇪", key: "SE", dial_code: "+46" },
  { name: "Switzerland", flag: "🇨🇭", key: "CH", dial_code: "+41" },
  { name: "Syrian Arab Republic", flag: "🇸🇾", key: "SY", dial_code: "+963" },
  { name: "Taiwan", flag: "🇹🇼", key: "TW", dial_code: "+886" },
  { name: "Tajikistan", flag: "🇹🇯", key: "TJ", dial_code: "+992" },
  {
    name: "Tanzania, United Republic of Tanzania",
    flag: "🇹🇿",
    key: "TZ",
    dial_code: "+255",
  },
  { name: "Thailand", flag: "🇹🇭", key: "TH", dial_code: "+66" },
  { name: "Timor-Leste", flag: "🇹🇱", key: "TL", dial_code: "+670" },
  { name: "Togo", flag: "🇹🇬", key: "TG", dial_code: "+228" },
  { name: "Tokelau", flag: "🇹🇰", key: "TK", dial_code: "+690" },
  { name: "Tonga", flag: "🇹🇴", key: "TO", dial_code: "+676" },
  { name: "Trinidad and Tobago", flag: "🇹🇹", key: "TT", dial_code: "+1868" },
  { name: "Tunisia", flag: "🇹🇳", key: "TN", dial_code: "+216" },
  { name: "Turkey", flag: "🇹🇷", key: "TR", dial_code: "+90" },
  { name: "Turkmenistan", flag: "🇹🇲", key: "TM", dial_code: "+993" },
  {
    name: "Turks and Caicos Islands",
    flag: "🇹🇨",
    key: "TC",
    dial_code: "+1649",
  },
  { name: "Tuvalu", flag: "🇹🇻", key: "TV", dial_code: "+688" },
  { name: "Uganda", flag: "🇺🇬", key: "UG", dial_code: "+256" },
  { name: "Ukraine", flag: "🇺🇦", key: "UA", dial_code: "+380" },
  { name: "United Arab Emirates", flag: "🇦🇪", key: "AE", dial_code: "+971" },
  { name: "United States", flag: "🇺🇸", key: "US", dial_code: "+1" },
  { name: "Uruguay", flag: "🇺🇾", key: "UY", dial_code: "+598" },
  { name: "Uzbekistan", flag: "🇺🇿", key: "UZ", dial_code: "+998" },
  { name: "Vanuatu", flag: "🇻🇺", key: "VU", dial_code: "+678" },
  {
    name: "Venezuela, Bolivarian Republic of Venezuela",
    flag: "🇻🇪",
    key: "VE",
    dial_code: "+58",
  },
  { name: "Vietnam", flag: "🇻🇳", key: "VN", dial_code: "+84" },
  {
    name: "Virgin Islands, British",
    flag: "🇻🇬",
    key: "VG",
    dial_code: "+1284",
  },
  { name: "Virgin Islands, U.S.", flag: "🇻🇮", key: "VI", dial_code: "+1340" },
  { name: "Wallis and Futuna", flag: "🇼🇫", key: "WF", dial_code: "+681" },
  { name: "Yemen", flag: "🇾🇪", key: "YE", dial_code: "+967" },
  { name: "Zambia", flag: "🇿🇲", key: "ZM", dial_code: "+260" },
  { name: "Zimbabwe", flag: "🇿🇼", key: "ZW", dial_code: "+263" },
];
